services:
  app-prod:
    build:
      context: .
      args:
        - NODE_ENV=production
    ports:
      - "3000:3000"
  app-dev:
    build:
      context: .
      target: deps
    command: npm run dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
  postgres:
    image: postgres:10.3
    restart: always
    container_name: ${PROJECT_NAME}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${PROJECT_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "${DB_PORT_STRING}"
volumes:
  postgres: